services:
  frontend-alexandrebonnin-fr:
    container_name: frontend-alexandrebonnin-fr
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports: 
      - "3001:3000"
    volumes:
      - ".:/alexandrebonnin-front"
      - "/alexandrebonnin-front/node_modules"
    command: sh -c "npm run start"