version: '3'

services:
  alexandrebonnin-front:
    image: abonnin37/alexandrebonnin-front-prod:latest
    env_file:
      - prod.env
    ports: 
      - "3001:3000"
    volumes:
      - ".:/alexandrebonnin-front"
      - "/alexandrebonnin-front/node_modules"
    command: sh -c "npm run start"