name: Build and deploy

on:
  push:
    branches: [ "test-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f Dockerfile.prod -t alexandrebonnin-front-prod:latest .

    - name: Login to DockerHub registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKERHUB_USERNAME }}"/alexandrebonnin-front-prod:latest

    - name: test
      run: echo "valid 2"
    